### PR TITLE
MXC6255XC accelerometer

### PR DESCRIPTION
**Pull request by 1019gene**

### CODE REVIEW

**Comment by Matthew-Klock** [comment]
Sorry, I set up the repository without the required permissions. If you could add your device to our shared library and make another pull request that would be appreciated.

**Comment by Matthew-Klock** [comment]
Also, next time, write a description of what you did in the pull request

**Comment by 1019gene** [comment]
Do I go through all the upload steps again? Or do I just directly make another pull request? Because it says that Pod4 is all up to date with my branch.

Thanks!
Gene

**Comment by Matthew-Klock** [comment]
No, add your part to the common library in eagle (in the hyperloop library folder, pod4.lbr) and then redo the request. The 'git commit -m "some message"' 'git push origin Gene_Lee'. The differences should be in 'pod4.lbr'. The goal is to have a common library that we all contribute our parts to so we don't have to import a million individual libraries.

**Comment by Matthew-Klock** [comment]
Sorry, I should have specified this before. This is a new platform for the PCB team and there is going to be a bit of a learning curve, but I think this will make it easier to be collaborative.

**Pull request merged**
