### PR TITLE
Gene lee

### PR DESCRIPTION
**Pull request by 1019gene**
Uploading MXC6255XC accelerometer

### CODE REVIEW

**Comment by Matthew-Klock** [comment]
Put pod4.lbr in the hyperloop library folder

**Comment by Matthew-Klock** [comment]
Make it the pod4.lbr file. There should be conflicts

**Comment by 1019gene** [comment]
Can I shut down my branch and completely redo it? Sorry for all the inconveniences…. This is my first time using GitHub…..

**Comment by Matthew-Klock** [comment]
Sure, basically just open pod4.lbr in Eagle, import your part, and commit. It should say you are changing a file. Then push it to your branch, then submit a pull request on here. It's a learning curve but it's a really good skill to learn.

**Comment by 1019gene** [comment]
Alright :)  I think I got it now? Could you verify for me to see if I did everything correctly?

THANK YOU SO MUCH

**Pull request closed without merging**
